version: '3.8'

services:
  apache:
    image: Dockerfile
    container_name: apache-web
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - tomcat
    restart: unless-stopped  

  tomcat:
    image: tomcat:9.0
    container_name: tomcat-server
    expose:
      - "8080"
    volumes:
      - ./webapps/:/usr/local/tomcat/webapps/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge