version: '3'

services:
  tomcat:
    image: tomcat:9.0 
    container_name: tomcat_app
    ports:
      - "8080:8080"  
    volumes:
      - ./hello-world.war:/usr/local/tomcat/webapps/app1.war  # Monta tu WAR en la carpeta de despliegue
      - ./sample.war:/usr/local/tomcat/webapps/app2.war  # Monta tu WAR en la carpeta de despliegue
    restart: always

  apache:
    image: httpd:2.4
    container_name: apache
    depends_on:
      - tomcat  
    ports:
      - "80:80"  
      - "443:443"
    volumes:
      - ./apache.conf:/usr/local/apache2/conf/httpd.conf:ro  
      - ./default-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro
      - ../certificado:/usr/local/apache2/conf/cert:ro
    restart: always
