version: '3.8'

services:
  apache:
    image: httpd:2.4
    container_name: apache-web
    ports:
      - "80:80"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - app-network
    depends_on:
      - tomcat

  tomcat:
    image: tomcat:9.0
    container_name: tomcat-server
    expose:
      - "8080"
    volumes:
      - ./webapps/:/usr/local/tomcat/webapps/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge